<a href="https://colab.research.google.com/github/VaibhaviDeveloper/MSIS_AML/blob/main/AMLlab2Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
m=np.array([[1,2,3],
            [4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
m.shape

(2, 3)

In [ ]:
n=np.arange(0,30,2)

In [ ]:
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
c=np.arange(30,0,-2)
c

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
n=n.reshape(3,5)

In [ ]:
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
lspace=np.linspace(0,10,9)
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [ ]:
lspace.resize(3,3)
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [ ]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
num=np.matrix([[11,12,13],
               [2,3,4],
               [3,4,5]])
num

matrix([[11, 12, 13],
        [ 2,  3,  4],
        [ 3,  4,  5]])

In [ ]:
type(num)

numpy.matrix

In [ ]:
print("Main Diagnol Elements:\n" , np.diag(num))
print("Diagnol elements above the main diagnol : \n" , np.diag(num,1))
print("Diagnol elements below the main diagnol : \n",np.diag(num,-1))
print("Diagnol elements one step above main diagnol : \n" , np.diag(num,2))
print("Diagnol elements one step below main diagnol : \n", np.diag(num,-2))

Main Diagnol Elements:
 [11  3  5]
Diagnol elements above the main diagnol : 
 [12  4]
Diagnol elements below the main diagnol : 
 [2 4]
Diagnol elements one step above main diagnol : 
 [13]
Diagnol elements one step below main diagnol : 
 [3]


In [ ]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
p=np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [ ]:
np.vstack([p,2*p,3*p])

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x)
print(y)

[1 2 3]
[4 5 6]


In [ ]:
print(x+y)
print(x-y)

[5 7 9]
[-3 -3 -3]


In [ ]:
print(x*y)
print(x@y) #Multiply and add , similar to dot product
print(x**2)

[ 4 10 18]
32
[1 4 9]


In [ ]:
#Dot Product
x.dot(y) # dot product 1*4+2*5+3*6

np.int64(32)

In [ ]:
z=np.array([y,y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
print(len(z)) # Number of rows of array

2


In [ ]:
# The shape of array z is (2,3) before transposing
z.shape

(2, 3)

In [ ]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.T.shape

(3, 2)

In [ ]:
z.dtype

dtype('int64')

In [ ]:
z=z.astype('f')
z.dtype

dtype('float32')

In [ ]:
# Math Functions
# Numpy has many built in math functions that can be performed on arrays.

a=np.array([-4,-2,1,3,5])
a.sum()

np.int64(3)

In [ ]:
a.max()

np.int64(5)

In [ ]:
a.min()

np.int64(-4)

In [ ]:
a.mean()

np.float64(0.6)

In [ ]:
a.std()

np.float64(3.2619012860600183)

In [ ]:
a.argmax()

np.int64(4)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
# Indexing / Slicing
import numpy as np
s = np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
s.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
# Use bracket notation to get the value at a specific index . Remember that indexing starts from 0

s[0] , s[4] ,s[-1]

(np.int64(0), np.int64(16), np.int64(25))

In [ ]:
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [ ]:
s[0],s[4],s[-1]

(np.int64(0), np.int64(16), np.int64(144))

In [ ]:
s[1:5]

array([ 1,  4,  9, 16])

In [ ]:
s[-4:]

array([ 81, 100, 121, 144])

In [ ]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [ ]:
s[-5::2]

array([ 64, 100, 144])

In [ ]:
r=np.arange(100).reshape(10,10)

In [ ]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
r[3,4]

np.int64(34)

In [ ]:
r[2,1:4]

array([21, 22, 23])

In [ ]:
r[:3,:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])

In [ ]:
r[3,3:6]

array([33, 34, 35])

In [ ]:
# This is a slice of the last row , and only every other element
r[-1,::2]

array([90, 92, 94, 96, 98])

In [ ]:
# We can also perform conditional indexing . Here we are selecting values from the array
r[r>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
       82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98,
       99])

In [ ]:
# WE can assign all values in the array that are greater than 30 to the value
r[r>30]=30

In [ ]:
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
r2[:]=0

In [ ]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# r has also changed
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
# To avoid this , use r.copy
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
r_copy[:]=10

In [ ]:
r_copy

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [ ]:
r

array([[ 0,  0,  0,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  0,  0, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  0,  0, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [ ]:
test = np.random.randint(0,10,(4,3))
test

array([[2, 2, 1],
       [7, 8, 5],
       [0, 8, 6],
       [3, 3, 6]])

In [ ]:
# Iterate by rows
for row in test:
  print(row)

[2 2 1]
[7 8 5]
[0 8 6]
[3 3 6]


In [ ]:
for i in range(len(test)):
  print(test[i])

[2 2 1]
[7 8 5]
[0 8 6]
[3 3 6]


In [ ]:
for i,row in enumerate(test):
  print('row' , i , 'is',row)

row 0 is [2 2 1]
row 1 is [7 8 5]
row 2 is [0 8 6]
row 3 is [3 3 6]


In [ ]:
test2=test**2
test2

array([[ 4,  4,  1],
       [49, 64, 25],
       [ 0, 64, 36],
       [ 9,  9, 36]])

In [ ]:
for i,j in zip(test,test2):
  print(i,'+',j,'=',i+j)

[2 2 1] + [4 4 1] = [6 6 2]
[7 8 5] + [49 64 25] = [56 72 30]
[0 8 6] + [ 0 64 36] = [ 0 72 42]
[3 3 6] + [ 9  9 36] = [12 12 42]


In [ ]:
# axis=0 means column wise operation
# axis =1 means row wise operation

In [ ]:
marks=np.array([
    [80,75,89],
    [1,2,3],
    [4,5,6]
])
marks

array([[80, 75, 89],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [ ]:
student_total = np.sum(marks,axis=1)

In [ ]:
print("Total of each student : ",student_total)

Total of each student :  [244   6  15]


In [ ]:
student_average = np.mean(marks,axis=1)
print("Average of each student : ",student_average)

Average of each student :  [81.33333333  2.          5.        ]


In [ ]:
subject_average=np.mean(marks,axis=0)
print("Average of each subject : ",subject_average)

Average of each subject :  [28.33333333 27.33333333 32.66666667]


In [ ]:
highest_student=np.argmax(student_total)
print("Highest marks of each student : ",highest_student+1)

Highest marks of each student :  1


In [ ]:
# Numpy Assignment

In [ ]:
# Create a constant array
# Prints "[[ 7.  7.]
# [ 7.  7.]]"
arr1 = np.full((2,2),7,dtype=float)
print(arr1)

[[7. 7.]
 [7. 7.]]


In [ ]:
# Create an array filled with random values
# Might print "[[ 0.91940167  0.08143941]
#               [ 0.68744134  0.87236687]]"
arr2=np.random.rand(2,2)
print(arr2)

[[0.68227836 0.65178957]
 [0.86573811 0.84535532]]


In [ ]:
# Create a NumPy array containing the numbers from 10 to 50. Display:
values=np.arange(10,51)
# The array
print(values)
# Number of elements
print(values.size)
# Shape
print(values.shape)
# Dimension
values.ndim
# Data type
values.dtype

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)


dtype('int64')

In [ ]:
#Using NumPy, create:

# A 1D array containing 10 zeros
arr3=np.zeros(10)
print(arr3)
# A 1D array containing 10 ones
arr4=np.ones(10)
print(arr4)
# A 3 × 3 array containing ones
arr5=np.ones((3,3))
print(arr5)
# A 3 × 3 array containing zeros
arr6=np.zeros((3,3))
print(arr6)
# A 4 × 4 identity matrix
arr7=np.eye(4)
print(arr7)
# An array containing numbers from 5 to 50 with a step size of 5.
arr8=np.arange(5,51,5)
print(arr8)
# An array containing 10 random numbers between 0 and 100
arr9=np.random.randint(0,100,10)
print(arr9)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 5 10 15 20 25 30 35 40 45 50]
[82 32 25 14 45 55 88 86  4 22]


In [ ]:
# Create an array containing numbers from 1 to 24. Reshape it into:
arr10=np.arange(1,25)
print(arr10)
print(arr10.shape)
print(arr10.ndim)
# 4 × 6
arr11=arr10.reshape(4,6)
print(arr11)
print(arr11.shape)
print(arr11.ndim)
# 6 × 4
arr12=arr10.reshape(6,4)
print(arr12)
print(arr12.shape)
print(arr12.ndim)
# 2 × 12
arr13=arr10.reshape(2,12)
print(arr13)
print(arr13.shape)
print(arr13.ndim)
# 2 × 3 × 4
arr14=arr10.reshape(2,3,4)
print(arr14)
print(arr14.shape)
print(arr14.ndim)
# Display the shape and ndim of each result.


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)
1
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
(6, 4)
2
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
(2, 12)
2
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
3


In [ ]:
#Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
marks=np.array([78, 85, 92, 67, 88, 73, 95, 81])
#Write NumPy statements to display:

#First element
print("First element:",marks[0])
#Last element
print("Last element:",marks[-1])
#First four elements
print("First four elements:",marks[:4])
#Last three elements
print("Last three elements:",marks[-3:])
#Third element
print("Third element:",marks[2])


First element: 78
Last element: 81
First four elements: [78 85 92 67]
Last three elements: [73 95 81]
Third element: 92


In [ ]:
# Create:
# a = np.array([10, 20, 30, 40, 50])
# b = np.array([5, 10, 15, 20, 25])
a=np.array([10,20,30,40,50])
b=np.array([5,10,15,20,25])
# Calculate:

# a + b
print(a+b)
# a - b
print(a-b)
# a * b
print(a*b)
# a / b
print(a/b)
# Square of every element in a
print(a**2)

[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [ ]:
#Given:
#salary = np.array([25000, 32000, 28000, 45000,
#                 50000, 38000, 42000, 30000])
salary=np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])
#Find:

#Total salary
print("Total salary : ",salary.sum())
#Average salary
print("Average salary : ",salary.mean())
#Highest salary
print("Highest salary : ",salary.max())
#Lowest salary
print("Lowest salary : ",salary.min())
#Median salary
print("Median salary : ",np.median(salary))
#Standard deviation
print("Standard deviation : ",np.std(salary))

Total salary :  290000
Average salary :  36250.0
Highest salary :  50000
Lowest salary :  25000
Median salary :  35000.0
Standard deviation :  8317.902379807063


In [ ]:
#Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
# Using NumPy boolean indexing, find:

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

# Marks greater than 75
cond1=marks>75
result=marks[cond1]
print(result)

# Marks between 50 and 80
cond2=(marks>=50) & (marks<=80)
result=marks[cond2]
print(result)

# Number of students who scored below 50
cond3=marks<50
result=marks[cond3]
print(result.size)

#Percentage of students who scored 60 or above
cond4=marks>60
result=marks[cond4]
print((result.size)/(marks.size)*100)



[78 89 90 76 84]
[78 67 55 76]
3
60.0


In [ ]:
#10. The following array contains marks of four students in three subjects:

# marks = np.array([
#   [80, 75, 90],
#   [65, 70, 72],
#    [88, 92, 85],
#    [55, 60, 58]
# ])

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])
total_marks=np.sum(marks,axis=1)
print("Total marks of each student is :",total_marks)

average1 = np.mean(marks, axis=1)
print("Average marks of each student is :",average1)

average2 = np.mean(marks, axis=0)
print("Average marks in each subject :",average2)

print("Student with the highest total is :",total_marks.argmax()+1)

print("Highest mark in each subject is :",marks.max(axis=0))

Total marks of each student is : [245 207 265 173]
Average marks of each student is : [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject : [72.   74.25 76.25]
Student with the highest total is : 3
Highest mark in each subject is : [88 92 90]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
print("Matrix addition : \n",A+B)
print("Element wise matrix multiplication : \n",A*B)
print("Matrix multiplication : \n",A@B)
print("Transpose of A : \n",A.T)

Matrix addition : 
 [[ 6  8]
 [10 12]]
Element wise matrix multiplication : 
 [[ 5 12]
 [21 32]]
Matrix multiplication : 
 [[19 22]
 [43 50]]
Transpose of A : 
 [[1 3]
 [2 4]]


In [ ]:
# Daily temperatures for two weeks are:

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])
print("Mean temperature : ",temperature.mean())
print("Maximum and minimum temperatures : "  ,temperature.max(),"and",temperature.min())
avg=np.mean(temperature)
result=temperature[temperature>avg]
print("Number of days above the average temperature : ",len(result))
condition=temperature>34
print("Temperature greater than 34 : ",temperature[condition])
diff=temperature.max()-temperature.min()
print("Difference between maximum and minimum temperature : ",diff)
std=np.std(temperature)
print("Standard deviation : ",std)

Mean temperature :  33.142857142857146
Maximum and minimum temperatures :  37 and 29
Number of days above the average temperature :  6
Temperature greater than 34 :  [35 36 35 37 36]
Difference between maximum and minimum temperature :  8
Standard deviation :  2.356060357495806


In [ ]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])
print("Total annual sales : ",sales.sum())
print("Average monthly sales : ",sales.mean())
# Month with the highest sales
print("Month with the highest sales : ",sales.argmax()+1)
print("Month with the lowest sales : ",sales.argmin()+1)
condition2=sales>20000
print("Months with sales greater than 20000 : ",len(sales[condition2]))
# Percentage increase from January to December
increase=(sales[-1]-sales[0])/sales[0]*100
print("Percentage increase from January to December : ",increase)

Total annual sales :  240000
Average monthly sales :  20000.0
Month with the highest sales :  12
Month with the lowest sales :  1
Months with sales greater than 20000 :  6
Percentage increase from January to December :  133.33333333333331


In [ ]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])
# Total marks of every student
total_marks=np.sum(marks,axis=1)
print(total_marks)

[341 275 366 235 316]
